/**
 * Short quotations and excerpts from Lewis Carroll's public-domain
 * Alice's Adventures in Wonderland (1865), chapters I–XII.
 * Source: https://www.gutenberg.org/files/11/11-h/11-h.htm
 * English wording is retained; fragments omit surrounding narration.
 * These entries do not include Through the Looking-Glass or adaptations.
 */
export const ALICE_THINKING_QUOTES = [
  {
    id: 'alice-001',
    text: "Alice had begun to think that very few things indeed were really impossible.",
    speaker: "Narrator",
    chapter: 1,
  },
  {
    id: 'alice-002',
    text: "Oh dear! Oh dear! I shall be late!",
    speaker: "White Rabbit",
    chapter: 1,
  },
  {
    id: 'alice-003',
    text: "Down, down, down. Would the fall never come to an end?",
    speaker: "Narrator",
    chapter: 1,
  },
  {
    id: 'alice-004',
    text: "I wonder how many miles I’ve fallen by this time?",
    speaker: "Alice",
    chapter: 1,
  },
  {
    id: 'alice-005',
    text: "I wonder if I shall fall right through the earth!",
    speaker: "Alice",
    chapter: 1,
  },
  {
    id: 'alice-006',
    text: "But do cats eat bats, I wonder?",
    speaker: "Alice",
    chapter: 1,
  },
  {
    id: 'alice-007',
    text: "Oh, how I wish I could shut up like a telescope!",
    speaker: "Alice",
    chapter: 1,
  },
  {
    id: 'alice-008',
    text: "I think I could, if I only knew how to begin.",
    speaker: "Alice",
    chapter: 1,
  },
  {
    id: 'alice-009',
    text: "What a curious feeling!",
    speaker: "Alice",
    chapter: 1,
  },
  {
    id: 'alice-010',
    text: "Come, there’s no use in crying like that!",
    speaker: "Alice",
    chapter: 1,
  },
  {
    id: 'alice-011',
    text: "Curiouser and curiouser!",
    speaker: "Alice",
    chapter: 2,
  },
  {
    id: 'alice-012',
    text: "Good-bye, feet!",
    speaker: "Alice",
    chapter: 2,
  },
  {
    id: 'alice-013',
    text: "I wonder if I’ve been changed in the night?",
    speaker: "Alice",
    chapter: 2,
  },
  {
    id: 'alice-014',
    text: "Who in the world am I? Ah, that’s the great puzzle!",
    speaker: "Alice",
    chapter: 2,
  },
  {
    id: 'alice-015',
    text: "I’ll try if I know all the things I used to know.",
    speaker: "Alice",
    chapter: 2,
  },
  {
    id: 'alice-016',
    text: "That was a narrow escape!",
    speaker: "Alice",
    chapter: 2,
  },
  {
    id: 'alice-017',
    text: "However, everything is queer to-day.",
    speaker: "Alice",
    chapter: 2,
  },
  {
    id: 'alice-018',
    text: "Would you like cats if you were me?",
    speaker: "Mouse",
    chapter: 2,
  },
  {
    id: 'alice-019',
    text: "Sit down, all of you, and listen to me!",
    speaker: "Mouse",
    chapter: 3,
  },
  {
    id: 'alice-020',
    text: "Speak English!",
    speaker: "Eaglet",
    chapter: 3,
  },
  {
    id: 'alice-021',
    text: "the best way to explain it is to do it.",
    speaker: "Dodo",
    chapter: 3,
  },
  {
    id: 'alice-022',
    text: "the exact shape doesn’t matter",
    speaker: "Dodo",
    chapter: 3,
  },
  {
    id: 'alice-023',
    text: "Everybody has won, and all must have prizes.",
    speaker: "Dodo",
    chapter: 3,
  },
  {
    id: 'alice-024',
    text: "Mine is a long and a sad tale!",
    speaker: "Mouse",
    chapter: 3,
  },
  {
    id: 'alice-025',
    text: "What are you thinking of?",
    speaker: "Mouse",
    chapter: 3,
  },
  {
    id: 'alice-026',
    text: "Please come back and finish your story!",
    speaker: "Alice",
    chapter: 3,
  },
  {
    id: 'alice-027',
    text: "How surprised he’ll be when he finds out who I am!",
    speaker: "Alice",
    chapter: 4,
  },
  {
    id: 'alice-028',
    text: "I know something interesting is sure to happen",
    speaker: "Alice",
    chapter: 4,
  },
  {
    id: 'alice-029',
    text: "so I’ll just see what this bottle does.",
    speaker: "Alice",
    chapter: 4,
  },
  {
    id: 'alice-030',
    text: "There ought to be a book written about me, that there ought!",
    speaker: "Alice",
    chapter: 4,
  },
  {
    id: 'alice-031',
    text: "I wonder what they’ll do next!",
    speaker: "Alice",
    chapter: 4,
  },
  {
    id: 'alice-032',
    text: "Let me see—how is it to be managed?",
    speaker: "Alice",
    chapter: 4,
  },
  {
    id: 'alice-033',
    text: "but the great question is, what?",
    speaker: "Alice",
    chapter: 4,
  },
  {
    id: 'alice-034',
    text: "Who are you?",
    speaker: "Caterpillar",
    chapter: 5,
  },
  {
    id: 'alice-035',
    text: "I can’t explain myself, I’m afraid, sir",
    speaker: "Alice",
    chapter: 5,
  },
  {
    id: 'alice-036',
    text: "because I’m not myself, you see.",
    speaker: "Alice",
    chapter: 5,
  },
  {
    id: 'alice-037',
    text: "being so many different sizes in a day is very confusing.",
    speaker: "Alice",
    chapter: 5,
  },
  {
    id: 'alice-038',
    text: "I think, you ought to tell me who you are, first.",
    speaker: "Alice",
    chapter: 5,
  },
  {
    id: 'alice-039',
    text: "I’ve something important to say!",
    speaker: "Caterpillar",
    chapter: 5,
  },
  {
    id: 'alice-040',
    text: "Keep your temper",
    speaker: "Caterpillar",
    chapter: 5,
  },
  {
    id: 'alice-041',
    text: "What size do you want to be?",
    speaker: "Caterpillar",
    chapter: 5,
  },
  {
    id: 'alice-042',
    text: "only one doesn’t like changing so often, you know.",
    speaker: "Alice",
    chapter: 5,
  },
  {
    id: 'alice-043',
    text: "Are you content now?",
    speaker: "Caterpillar",
    chapter: 5,
  },
  {
    id: 'alice-044',
    text: "You’ll get used to it in time",
    speaker: "Caterpillar",
    chapter: 5,
  },
  {
    id: 'alice-045',
    text: "One side will make you grow taller, and the other side will make you grow shorter.",
    speaker: "Caterpillar",
    chapter: 5,
  },
  {
    id: 'alice-046',
    text: "And now which is which?",
    speaker: "Alice",
    chapter: 5,
  },
  {
    id: 'alice-047',
    text: "Anything you like",
    speaker: "Footman",
    chapter: 6,
  },
  {
    id: 'alice-048',
    text: "Would you tell me, please, which way I ought to go from here?",
    speaker: "Alice",
    chapter: 6,
  },
  {
    id: 'alice-049',
    text: "That depends a good deal on where you want to get to",
    speaker: "Cheshire Cat",
    chapter: 6,
  },
  {
    id: 'alice-050',
    text: "Then it doesn’t matter which way you go",
    speaker: "Cheshire Cat",
    chapter: 6,
  },
  {
    id: 'alice-051',
    text: "so long as I get somewhere",
    speaker: "Alice",
    chapter: 6,
  },
  {
    id: 'alice-052',
    text: "if you only walk long enough.",
    speaker: "Cheshire Cat",
    chapter: 6,
  },
  {
    id: 'alice-053',
    text: "What sort of people live about here?",
    speaker: "Alice",
    chapter: 6,
  },
  {
    id: 'alice-054',
    text: "we’re all mad here. I’m mad. You’re mad.",
    speaker: "Cheshire Cat",
    chapter: 6,
  },
  {
    id: 'alice-055',
    text: "How do you know I’m mad?",
    speaker: "Alice",
    chapter: 6,
  },
  {
    id: 'alice-056',
    text: "or you wouldn’t have come here.",
    speaker: "Cheshire Cat",
    chapter: 6,
  },
  {
    id: 'alice-057',
    text: "Call it what you like",
    speaker: "Cheshire Cat",
    chapter: 6,
  },
  {
    id: 'alice-058',
    text: "You’ll see me there",
    speaker: "Cheshire Cat",
    chapter: 6,
  },
  {
    id: 'alice-059',
    text: "I thought it would",
    speaker: "Cheshire Cat",
    chapter: 6,
  },
  {
    id: 'alice-060',
    text: "but a grin without a cat!",
    speaker: "Alice",
    chapter: 6,
  },
  {
    id: 'alice-061',
    text: "There’s plenty of room!",
    speaker: "Alice",
    chapter: 7,
  },
  {
    id: 'alice-062',
    text: "Why is a raven like a writing-desk?",
    speaker: "Hatter",
    chapter: 7,
  },
  {
    id: 'alice-063',
    text: "I’m glad they’ve begun asking riddles.",
    speaker: "Alice",
    chapter: 7,
  },
  {
    id: 'alice-064',
    text: "Then you should say what you mean",
    speaker: "March Hare",
    chapter: 7,
  },
  {
    id: 'alice-065',
    text: "Not the same thing a bit!",
    speaker: "Hatter",
    chapter: 7,
  },
  {
    id: 'alice-066',
    text: "It was the best butter",
    speaker: "March Hare",
    chapter: 7,
  },
  {
    id: 'alice-067',
    text: "What a funny watch!",
    speaker: "Alice",
    chapter: 7,
  },
  {
    id: 'alice-068',
    text: "Have you guessed the riddle yet?",
    speaker: "Hatter",
    chapter: 7,
  },
  {
    id: 'alice-069',
    text: "I haven’t the slightest idea",
    speaker: "Hatter",
    chapter: 7,
  },
  {
    id: 'alice-070',
    text: "It’s always six o’clock now.",
    speaker: "Hatter",
    chapter: 7,
  },
  {
    id: 'alice-071',
    text: "it’s always tea-time, and we’ve no time to wash the things between whiles.",
    speaker: "Hatter",
    chapter: 7,
  },
  {
    id: 'alice-072',
    text: "But what happens when you come to the beginning again?",
    speaker: "Alice",
    chapter: 7,
  },
  {
    id: 'alice-073',
    text: "Suppose we change the subject",
    speaker: "March Hare",
    chapter: 7,
  },
  {
    id: 'alice-074',
    text: "Take some more tea",
    speaker: "March Hare",
    chapter: 7,
  },
  {
    id: 'alice-075',
    text: "it’s very easy to take more than nothing.",
    speaker: "Hatter",
    chapter: 7,
  },
  {
    id: 'alice-076',
    text: "Now, I’ll manage better this time",
    speaker: "Alice",
    chapter: 7,
  },
  {
    id: 'alice-077',
    text: "You shan’t be beheaded!",
    speaker: "Alice",
    chapter: 8,
  },
  {
    id: 'alice-078',
    text: "Can you play croquet?",
    speaker: "Queen of Hearts",
    chapter: 8,
  },
  {
    id: 'alice-079',
    text: "How are you getting on?",
    speaker: "Cheshire Cat",
    chapter: 8,
  },
  {
    id: 'alice-080',
    text: "It’s a friend of mine—a Cheshire Cat",
    speaker: "Alice",
    chapter: 8,
  },
  {
    id: 'alice-081',
    text: "I’d rather not",
    speaker: "Cheshire Cat",
    chapter: 8,
  },
  {
    id: 'alice-082',
    text: "A cat may look at a king",
    speaker: "Alice",
    chapter: 8,
  },
  {
    id: 'alice-083',
    text: "Everything’s got a moral, if only you can find it.",
    speaker: "Duchess",
    chapter: 9,
  },
  {
    id: 'alice-084',
    text: "Oh, ’tis love, ’tis love, that makes the world go round!",
    speaker: "Duchess",
    chapter: 9,
  },
  {
    id: 'alice-085',
    text: "Take care of the sense, and the sounds will take care of themselves.",
    speaker: "Duchess",
    chapter: 9,
  },
  {
    id: 'alice-086',
    text: "Be what you would seem to be",
    speaker: "Duchess",
    chapter: 9,
  },
  {
    id: 'alice-087',
    text: "I’ve a right to think",
    speaker: "Alice",
    chapter: 9,
  },
  {
    id: 'alice-088',
    text: "You are all pardoned.",
    speaker: "King of Hearts",
    chapter: 9,
  },
  {
    id: 'alice-089',
    text: "Would you like to see a little of it?",
    speaker: "Mock Turtle",
    chapter: 10,
  },
  {
    id: 'alice-090',
    text: "We can do without lobsters, you know.",
    speaker: "Mock Turtle",
    chapter: 10,
  },
  {
    id: 'alice-091',
    text: "I never thought about it",
    speaker: "Alice",
    chapter: 10,
  },
  {
    id: 'alice-092',
    text: "but it’s no use going back to yesterday, because I was a different person then.",
    speaker: "Alice",
    chapter: 10,
  },
  {
    id: 'alice-093',
    text: "explanations take such a dreadful time.",
    speaker: "Gryphon",
    chapter: 10,
  },
  {
    id: 'alice-094',
    text: "There’s a great deal to come before that!",
    speaker: "White Rabbit",
    chapter: 11,
  },
  {
    id: 'alice-095',
    text: "you know you’re growing too.",
    speaker: "Alice",
    chapter: 11,
  },
  {
    id: 'alice-096',
    text: "I’d rather finish my tea",
    speaker: "Hatter",
    chapter: 11,
  },
  {
    id: 'alice-097',
    text: "Then it ought to be Number One",
    speaker: "Alice",
    chapter: 12,
  },
  {
    id: 'alice-098',
    text: "It proves nothing of the sort!",
    speaker: "Alice",
    chapter: 12,
  },
  {
    id: 'alice-099',
    text: "Begin at the beginning",
    speaker: "King of Hearts",
    chapter: 12,
  },
  {
    id: 'alice-100',
    text: "Sentence first—verdict afterwards.",
    speaker: "Queen of Hearts",
    chapter: 12,
  },
] as const;
