import { useRef, useState } from 'react';
import { FilePlus, FolderPlus, Trash2 } from 'lucide-react';
import type { HomiePackFile } from '../../../../shared/homie-pack';
import { NeumorphicButton, NeumorphicTextField, LiquidGlassSelect } from '../../shared/ui';
import { TooltipButton } from '../../shared/ui/TooltipButton';
import { createPackSkill, readSelectedPackFiles } from './homiePackAuthoring';
import form from './SpecialistAgentForm.module.css';
import styles from './HomieSettings.module.css';

type AssetsProps = { files: HomiePackFile[]; disabled: boolean; onChange(files: HomiePackFile[]): void; onError(message: string): void };

export function PackFilePicker({ files, disabled, onChange, onError, onBusy, target, folder = false }: AssetsProps & {
  target: 'skills' | 'scripts' | 'resources'; folder?: boolean; onBusy(value: boolean): void;
}) {
  const input = useRef<HTMLInputElement>(null);
  const pending = useRef(false);
  const label = target === 'skills' ? 'Import skill folder' : folder ? 'Add folder' : 'Add files';
  return <>
    <input hidden type="file" multiple aria-label={label} ref={element => {
      input.current = element;
      if (element && folder) element.setAttribute('webkitdirectory', '');
    }} disabled={disabled} onChange={event => {
      const selected = Array.from(event.currentTarget.files ?? []);
      event.currentTarget.value = '';
      if (!selected.length || pending.current || disabled) return;
      pending.current = true; onBusy(true);
      void readSelectedPackFiles(selected, target, files).then(onChange, error => onError(error instanceof Error ? error.message : 'Could not read the selected files.'))
        .finally(() => { pending.current = false; onBusy(false); });
    }} />
    <NeumorphicButton variant="ghost" disabled={disabled} onClick={() => input.current?.click()}>
      {folder ? <FolderPlus aria-hidden="true" /> : <FilePlus aria-hidden="true" />}{label}
    </NeumorphicButton>
  </>;
}

function SkillContent({ file, disabled, onChange }: { file: HomiePackFile; disabled: boolean; onChange(content: string): void }) {
  // Structured edits are restricted to the exact front matter generated by this editor.
  // Imported metadata is preserved verbatim through the source editor.
  const match = /^---\nname: ("[^\n]*")\ndescription: ("[^\n]*")\n---\n\n([\s\S]*)$/.exec(file.content);
  let parsed: { name: string; description: string; body: string } | null = null;
  if (match) {
    try {
      const name: unknown = JSON.parse(match[1]!), description: unknown = JSON.parse(match[2]!);
      if (typeof name === 'string' && typeof description === 'string') parsed = { name, description, body: match[3]! };
    } catch { /* Existing, non-generated front matter stays in the source editor. */ }
  }
  if (!parsed) return <label className={form.field}>Skill Markdown<NeumorphicTextField variant="standard" multiline rows={14}
    aria-label="Skill Markdown" value={file.content} disabled={disabled} onChange={event => onChange(event.target.value)} /></label>;
  const value = parsed;
  const update = (patch: Partial<typeof value>) => {
    const next = { ...value, ...patch };
    onChange(`---\nname: ${JSON.stringify(next.name)}\ndescription: ${JSON.stringify(next.description)}\n---\n\n${next.body}`);
  };
  return <>
    <label className={form.field}>Name<NeumorphicTextField variant="standard" aria-label="Edit skill name" value={value.name} disabled={disabled} onChange={event => update({ name: event.target.value })} /></label>
    <label className={form.field}>When to use<NeumorphicTextField variant="standard" aria-label="Edit skill description" value={value.description} disabled={disabled} onChange={event => update({ description: event.target.value })} /></label>
    <label className={form.field}>Instructions<NeumorphicTextField variant="standard" multiline rows={12} aria-label="Edit skill instructions" value={value.body} disabled={disabled} onChange={event => update({ body: event.target.value })} /></label>
  </>;
}

export function PackSkills(props: AssetsProps & { onBusy(value: boolean): void }) {
  const { files, disabled, onChange, onError } = props;
  const [name, setName] = useState(''), [description, setDescription] = useState(''), [instructions, setInstructions] = useState('');
  const [selected, setSelected] = useState('');
  const skills = files.filter(file => /^skills\/[^/]+\/SKILL\.md$/.test(file.path));
  const current = skills.find(file => file.path === selected);
  return <>
    <h3>Skills</h3>
    <p className={form.description}>Describe a reusable task. Cheshi creates its skill file and folder for you.</p>
    <div className={styles.list}>{skills.map(file => <div className={styles.row} key={file.path}>
      <NeumorphicButton variant="ghost" disabled={disabled} aria-pressed={selected === file.path} onClick={() => setSelected(file.path)}>{file.path.split('/')[1]}</NeumorphicButton>
      <TooltipButton variant="ghost" size="icon" title="Remove skill" aria-label={`Remove skill ${file.path.split('/')[1]}`} disabled={disabled} onClick={() => {
        onChange(files.filter(item => !item.path.startsWith(file.path.slice(0, -'SKILL.md'.length)))); setSelected('');
      }}><Trash2 aria-hidden="true" /></TooltipButton>
    </div>)}</div>
    {current ? <>
      <SkillContent file={current} disabled={disabled} onChange={content => onChange(files.map(file => file.path === current.path ? { ...file, content } : file))} />
      <NeumorphicButton variant="ghost" disabled={disabled} onClick={() => setSelected('')}>New skill</NeumorphicButton>
    </> : <>
      <label className={form.field}>Name<NeumorphicTextField variant="standard" aria-label="Skill name" value={name} disabled={disabled} onChange={event => setName(event.target.value)} /></label>
      <label className={form.field}>When to use<NeumorphicTextField variant="standard" aria-label="Skill description" value={description} disabled={disabled} onChange={event => setDescription(event.target.value)} /></label>
      <label className={form.field}>Instructions<NeumorphicTextField variant="standard" multiline rows={8} aria-label="Skill instructions" value={instructions} disabled={disabled} onChange={event => setInstructions(event.target.value)} /></label>
      <NeumorphicButton variant="standard" disabled={disabled || !name.trim() || !description.trim() || !instructions.trim()} onClick={() => {
        try {
          const file = createPackSkill(files, name, description, instructions);
          onChange([...files, file]); setSelected(file.path); setName(''); setDescription(''); setInstructions('');
        } catch (error) { onError(error instanceof Error ? error.message : 'Could not add skill.'); }
      }}>Add skill</NeumorphicButton>
    </>}
    <PackFilePicker {...props} target="skills" folder />
  </>;
}

export function PackFiles(props: AssetsProps & { onBusy(value: boolean): void }) {
  const { files, disabled, onChange } = props;
  const [target, setTarget] = useState<'scripts' | 'resources'>('scripts');
  const [selected, setSelected] = useState('');
  const file = files.find(item => item.path === selected);
  return <>
    <h3>Files</h3>
    <p className={form.description}>Add UTF-8 scripts or reference documents. Folder structure is preserved. Files are read-only in the worker.</p>
    <LiquidGlassSelect ariaLabel="Add files to" value={target} disabled={disabled} menuAppearance="toolbar" triggerAppearance="standard"
      options={[{ value: 'scripts', label: 'Scripts' }, { value: 'resources', label: 'Reference documents' }]} onChange={setTarget} />
    <div className={styles.actions}><PackFilePicker {...props} target={target} /><PackFilePicker {...props} target={target} folder /></div>
    <div className={styles.list}>{files.filter(item => !item.path.endsWith('/SKILL.md')).map(item => <div key={item.path} className={styles.row}>
      <NeumorphicButton variant="ghost" disabled={disabled} aria-pressed={selected === item.path} onClick={() => setSelected(item.path)}>{item.path}</NeumorphicButton>
      <TooltipButton variant="ghost" size="icon" title="Remove file" aria-label={`Remove ${item.path}`} disabled={disabled}
        onClick={() => { onChange(files.filter(entry => entry.path !== item.path)); setSelected(''); }}><Trash2 aria-hidden="true" /></TooltipButton>
    </div>)}</div>
    {file && <label className={form.field}>{file.path}<NeumorphicTextField variant="standard" multiline rows={14} aria-label="Homie pack file content" disabled={disabled}
      value={file.content} onChange={event => onChange(files.map(item => item.path === selected ? { ...item, content: event.target.value } : item))} /></label>}
  </>;
}
