export {
  createWorkspaceEntry,
  getWorkspaceEntryLocation,
  getWorkspaceFileVersion,
  listWorkspaceDirectory,
  MAX_EDITABLE_FILE_BYTES,
  moveWorkspaceEntry,
  readWorkspaceFile,
  readWorkspaceFileExcerpt,
  renameWorkspaceEntry,
  watchWorkspaceFiles,
  WorkspaceRequestError,
  writeWorkspaceFile,
  writeWorkspaceFiles,
} from '../../lib/workspace-file-service.mts';

export type {
  WorkspaceEntryCreateRequest,
  WorkspaceEntryCreateResult,
  WorkspaceFileEntry,
  WorkspaceFileExcerptRequest,
  WorkspaceFileExcerptResult,
  WorkspaceFileKind,
  WorkspaceFileReadResult,
  WorkspaceFileVersion,
  WorkspaceFileWriteRequest,
  WorkspaceFileWriteResult,
  WorkspaceFilesChangedEvent,
  WorkspaceFileWatchListener,
  WorkspaceFileWatchOptions,
  WorkspaceFileWatcher,
  WorkspaceFileWatcherFactory,
  WorkspaceFilesWriteRequest,
  WorkspaceFilesWriteResult,
  WorkspaceEntryLocation,
  WorkspaceEntryMoveRequest,
  WorkspaceEntryMoveResult,
  WorkspaceEntryRenameRequest,
  WorkspaceEntryRenameResult,
  WorkspaceLineEnding,
} from '../../lib/workspace-file-service.mts';
